### ISSUE TITLE
關於資料來源的期間

### ISSUE THREAD

**Issue by thisray** [zake7749/Gossiping-Chinese-Corpus#1]
您好

我把八卦版所有的文章爬完，也整理成類似的格式後
發現檔案大小和您所提供的 Gossiping-QA-Dataset.txt 差不多大
所以我猜您 README.md 中 `2015 年至 2017 年 6 月的文章` 
應該是 `2005 年` 才對 (八卦版第一篇文的日期)
XD

謝謝

**Comment by zake7749** [comment]
嗨，感謝您的回饋 :+1: 

我剛剛重新查找了一下，這個範圍應該是正確的，
只是我不確定是從 2015 年的什麼時候開始 (╥﹏╥)
所以沒有特別標注月份。

您應該是從第 1 頁開始爬到最近的頁數的吧 ？
不過其實第 1 頁到 623 頁都是被 M 起來的文章，
關於 M 文，在[Re: [問題] 文章標題前的符號](https://www.ptt.cc/bbs/PttNewhand/M.1265292872.A.991.html) 中有詳細的說明，
換句話說，那些只是 2005 年至 2016 年的一小部份文章，
剩下的文章大部份都已經被系統自動從 PTT 網頁版刪除掉了（聽說系統會維持在 200,000 篇），
所以在簡介中我標注的是從 2015 年開始。

**Comment by thisray** [comment]
原來是這樣呀
感謝你的回覆~~
